In [1]:
import pandas as pd
import numpy as np

In [2]:
all_df = pd.read_csv("../data/preprocess/all.csv")

In [3]:
all_df.head()

,segment_id,date,weekday,period,LOS,s_node_id,e_node_id,length,max_velocity,street_level,street_name,segment_type,long_snode,lat_snode,long_enode,lat_enode,street_type,updated_at,velocity
0,26,2021-04-16,4,period_0_30,A,366428456,366416066,0.116,40.0,4,Nguyễn Văn Bá,tertiary,106.768732,10.841506,106.769254,10.842422,tertiary,2021-04-16 00:55:31.333000+00:00,117
1,33,2020-08-02,6,period_23_30,C,366469460,3792257828,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-02 23:56:28.019000+00:00,34
2,33,2020-08-02,6,period_23_30,C,366469460,3792257828,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-02 23:59:28.137000+00:00,26
3,33,2020-08-03,0,period_0_00,D,366469460,3792257828,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-03 00:02:28.070000+00:00,2
4,33,2020-08-03,0,period_0_00,D,366469460,3792257828,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-03 00:05:28.204000+00:00,35

In [4]:
train_nodes = np.concatenate((
    all_df["s_node_id"].to_numpy(), 
    all_df["e_node_id"].to_numpy()
))
train_nodes.shape

(181876,)

# Xây dựng tập nút

## Gộp tất cả các nút

In [5]:
nodes = np.sort(np.unique(train_nodes)).tolist()
nodes[:5]

[366367392, 366367451, 366367839, 366367847, 366368010]

## Chuyển node_id thành index mới

In [6]:
id_2_index = dict()
index_2_id = dict()

for index, _id in enumerate(nodes):
    id_2_index[_id] = index
    index_2_id[index] = _id

for i, (k, v) in enumerate(id_2_index.items()):
    if i >= 5:
        break
    print(k, v)

for i, (k, v) in enumerate(index_2_id.items()):
    if i >= 5:
        break
    print(k, v)

366367392 0
366367451 1
366367839 2
366367847 3
366368010 4
0 366367392
1 366367451
2 366367839
3 366367847
4 366368010

In [7]:
all_df["s_node_id"] = all_df["s_node_id"].map(lambda x: id_2_index[x])
all_df["e_node_id"] = all_df["e_node_id"].map(lambda x: id_2_index[x])
all_df.head()

,segment_id,date,weekday,period,LOS,s_node_id,e_node_id,length,max_velocity,street_level,street_name,segment_type,long_snode,lat_snode,long_enode,lat_enode,street_type,updated_at,velocity
0,26,2021-04-16,4,period_0_30,A,663,512,0.116,40.0,4,Nguyễn Văn Bá,tertiary,106.768732,10.841506,106.769254,10.842422,tertiary,2021-04-16 00:55:31.333000+00:00,117
1,33,2020-08-02,6,period_23_30,C,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-02 23:56:28.019000+00:00,34
2,33,2020-08-02,6,period_23_30,C,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-02 23:59:28.137000+00:00,26
3,33,2020-08-03,0,period_0_00,D,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-03 00:02:28.070000+00:00,2
4,33,2020-08-03,0,period_0_00,D,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-03 00:05:28.204000+00:00,35

# Xây dựng tập cạnh

In [8]:
segments = np.sort(np.unique(all_df["segment_id"])).tolist()
segments[:5]

[26, 33, 67, 70, 71]

In [9]:
segment_id_2_idx = dict()
idx_2_segment_id = dict()

for index, _id in enumerate(segments):
    segment_id_2_idx[_id] = index
    idx_2_segment_id[index] = _id

In [10]:
all_df["segment_id"] = all_df["segment_id"].map(lambda x: segment_id_2_idx[x])
all_df.head()

,segment_id,date,weekday,period,LOS,s_node_id,e_node_id,length,max_velocity,street_level,street_name,segment_type,long_snode,lat_snode,long_enode,lat_enode,street_type,updated_at,velocity
0,0,2021-04-16,4,period_0_30,A,663,512,0.116,40.0,4,Nguyễn Văn Bá,tertiary,106.768732,10.841506,106.769254,10.842422,tertiary,2021-04-16 00:55:31.333000+00:00,117
1,1,2020-08-02,6,period_23_30,C,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-02 23:56:28.019000+00:00,34
2,1,2020-08-02,6,period_23_30,C,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-02 23:59:28.137000+00:00,26
3,1,2020-08-03,0,period_0_00,D,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-03 00:02:28.070000+00:00,2
4,1,2020-08-03,0,period_0_00,D,1179,5601,0.026,40.0,3,Đường số 5,secondary,106.761957,10.878650,106.762143,10.878808,secondary,2020-08-03 00:05:28.204000+00:00,35

In [11]:
edges = all_df[["segment_id", "s_node_id", "e_node_id"]].drop_duplicates().to_numpy()
edges = edges[edges[:, 0].argsort()]
edges = edges[:, 1:]
edges = edges.T
edges.shape

(2, 10027)

# Kiểm tra thuộc tính động, tĩnh của dữ liệu

In [12]:
max_len_dict = {}

for col in all_df.columns:
    max_len_dict[col] = all_df.groupby("segment_id")[col].nunique().max()

In [13]:
max_len_dict

{'segment_id': np.int64(1),
 'date': np.int64(28),
 'weekday': np.int64(7),
 'period': np.int64(26),
 'LOS': np.int64(6),
 's_node_id': np.int64(1),
 'e_node_id': np.int64(1),
 'length': np.int64(1),
 'max_velocity': np.int64(1),
 'street_level': np.int64(1),
 'street_name': np.int64(1),
 'segment_type': np.int64(1),
 'long_snode': np.int64(1),
 'lat_snode': np.int64(1),
 'long_enode': np.int64(1),
 'lat_enode': np.int64(1),
 'street_type': np.int64(1),
 'updated_at': np.int64(2150),
 'velocity': np.int64(42)}

In [14]:
# DS thuộc tính nút
static_node_features = ["long_snode", "lat_snode", "long_enode", "lat_enode"]

In [15]:
# DS thuộc tính cạnh
static_edge_features = ["length", 'max_velocity', "street_level", "segment_type", "street_type"]

In [16]:
# DS thuộc tính dôộng
dynamic_features = ["LOS", "velocity", "weekday"]

# Xây dựng đặc trưng tĩnh

## Xây dựng đặc trưng cạnh

In [18]:
segments_df = all_df[["segment_id"] + static_edge_features].copy()

In [19]:
segment_type_oh = pd.get_dummies(segments_df, columns=["segment_type", ])
segment_type_oh.head()

,bank,bus_station,car,cinema,clothes,company,convenience,fuel,government,house,...,residential,school,secondary,secondary_link,tertiary,tertiary_link,trunk,trunk_link,unclassified,university
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [17]:
static_edge_feature = all_df[["segment_id"] + static_edge_features]
static_edge_feature = static_edge_feature.sort_values(by="segment_id").drop_duplicates().to_numpy()
static_edge_feature

array([[0, 0.116, 40.0, 4, 'tertiary', 'tertiary'],
       [1, 0.026, 40.0, 3, 'secondary', 'secondary'],
       [2, 0.007, 40.0, 3, 'secondary', 'secondary'],
       ...,
       [10024, 0.126, 40.0, 4, 'tertiary', 'tertiary'],
       [10025, 0.089, 40.0, 4, 'tertiary', 'tertiary'],
       [10026, 0.139, 40.0, 4, 'unclassified', 'unclassified']],
      shape=(10027, 6), dtype=object)